# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u6807\u9898')),
                ('content', models.TextField(help_text='\u535a\u5ba2\u5185\u5bb9')),
                ('pub_time', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
        ),
    ]
